### ISSUE TITLE
Add service account into function, in order to run function API. 

### ISSUE THREAD

**Issue by yinghli** [GoogleCloudPlatform/solutions-floating-ip-patterns-terraform#100]
resource "google_cloudfunctions_function" "function_switch" {
  depends_on  = [google_project_service.required_api]
  name        = "switch-route"
  description = "Function to switch route to primary or secondary VM"
  runtime     = "python38"

  available_memory_mb   = 256
  source_archive_bucket = google_storage_bucket.function_bucket.name
  source_archive_object = google_storage_bucket_object.function_archive.name
 # ++ add service account. 
  service_account_email = google_service_account.function_service_account.email
  trigger_http          = true
  entry_point           = "main"
}

**Comment by eeaton** [comment]
This has been addressed in PR #745  , thanks for the feedback
